/** @format */

import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import { ClerkProvider, ClerkLoaded, ClerkLoading } from '@clerk/nextjs';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <div className="mx-36 text-2xl">
            <ClerkLoading>
              <div className="flex flex-col items-center text-center mt-32">
                LOADING...
              </div>
            </ClerkLoading>
            <ClerkLoaded>
              <Navbar />
              {children}
            </ClerkLoaded>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
